name: Create Release
run-name: Resume Release
on:
    workflow_run:
        workflows: ['Build']
        types: [completed]
jobs:
    release:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
            - uses: boonya/gh-action-name-generator@v1
              id: generator
            - run: echo "Generated name is ${{ steps.generator.outputs.name }}."
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Create Release
              id: create_release
              uses: svenstaro/upload-release-action@v2
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: Sathya_Bhat_Resume_Latest.pdf
                asset_name: ${{ steps.generator.outputs.name }} Latest Resume
                tag: ${{ steps.generator.outputs.name }}
                overwrite: true
                body: "Sample Text"
